- .pre-commit-config.yaml
- mdit_py_plugins/anchors/index.py
- mdit_py_plugins/tasklists/__init__.py
- tests/test_myst_block.py
This commit ensures `Token.attrSet` is used instead,
in anticipation of the upstream format of `Token.attrs`.
> 👌 IMPROVE: Remove direct use of `Token.attrs`

- .flake8
- .github/workflows/tests.yml
- .mypy.ini
- .pre-commit-config.yaml
- mdit_py_plugins/front_matter/index.py
- pyproject.toml
- setup.cfg
- setup.py
- tests/fixtures/footnote.md
- tests/test_front_matter.py
- Update setup to static configuration
- Add yproject.toml
- Update pre-commit  hooks
- Add footnote test for recent fix
- Fix mypy fail for front_matter `Token.meta`
(we parse `Token.content`, so this is not necessary)
> ⬆️ UPDATE: markdown-it-py~=1.0

- mdit_py_plugins/dollarmath/index.py
- tests/fixtures/dollar_math.md
- tests/test_dollarmath.py
Switched on using the `double_inline` variable
(currently `False` by default)
> 👌 IMPROVE: Allow inline double-dollar (dollarmath_plugin)

- .readthedocs.yml
- MANIFEST.in
- docs/conf.py
- docs/index.md
- mdit_py_plugins/myst_blocks/index.py
- mdit_py_plugins/myst_role/index.py
- setup.cfg
- tox.ini
Adapted from markdown-it-py plugins.md,
which will be removed and reference this.
> 📚 DOCS: Add documentation!

- mdit_py_plugins/myst_blocks/index.py
- tests/fixtures/myst_block.md
- tests/test_myst_block.py
Closes https://github.com/executablebooks/MyST-Parser/issues/349
Also changes HTML comment tags from `` to ``. If there was a good reason for using three hyphens, then sorry, pls let me know, and I'll revert that change.
> 👌 IMPROVE: Parse multiline MyST comments

- mdit_py_plugins/amsmath/__init__.py
- tests/fixtures/amsmath.md
Changed the default rendering to: `<div class="math amsmath">{content}</div>`.
Added some tests to cover more realistic AMS math scenarios.
See also:
https://github.com/executablebooks/markdown-it-amsmath/pull/4
https://github.com/executablebooks/markdown-it-amsmath/issues/1
> 👌 IMPROVE: AMSmath defaut HTML tags

- mdit_py_plugins/dollarmath/index.py
- setup.cfg
- tests/fixtures/dollar_math.md
- tests/test_dollarmath.py
- tests/test_dollarmath/test_plugin_parse.yml
Syncs with: https://github.com/executablebooks/markdown-it-dollarmath/commit/543108e065cc9832f63d2f7e34bf43d7e0f1e5c5
closes #26
> 👌 IMPROVE: dollarmath plugin rendering

- mdit_py_plugins/amsmath/__init__.py
syncs with: https://github.com/executablebooks/markdown-it-amsmath/commit/d20e2fc310767ce53aef2277674d290ade1dddc8
> 👌 IMPROVE: Add renderer option to amsmath plugin

- mdit_py_plugins/myst_blocks/index.py
- tests/fixtures/myst_block.md
Match characters instead of using regex.
This now allows for an unlimited target length and whitespace in the target.
Also improve default rendering, inline with https://github.com/executablebooks/myst-vs-code
closes #28
> 👌 IMPROVE: MyST target block parsing

- mdit_py_plugins/myst_role/index.py
- tests/fixtures/myst_role.md
Match characters instead of using regex.
This now allows for an unlimited name length and new lines in the content.
> 👌 IMPROVE: MyST role syntax parsing

- mdit_py_plugins/footnote/index.py
- tests/fixtures/footnote.md
Closes https://github.com/executablebooks/mdit-py-plugins/issues/48
This merely fixes a porting issue -- Javascript upstream already works like this.
> 🐛 FIX: Parsing when newline is between footnote ID and first paragraph

- mdit_py_plugins/anchors/index.py
The anchors plugin remembered used anchor ids per MarkdownIt object for entire lifetime of the object. This means if you use the same MarkdownIt object to render multiple documents then the generated anchor ids will be affected by the order of rendered documents.
This PR makes it clear the known ids after anchors are generated, so separate renders should not affect each other.
This seems like a safe fix to my eyes but I haven't examined these systems in-depth. It does past the single anchors test still.
> 🐛: Anchor ids in separate renders should not affect each other.

- .pre-commit-config.yaml
flake8 has been removed from gitlab so the URL needs to be fixed in .pre-commit-config.yaml
> 🔧 MAINTAIN: Fix pre-commit configuration

- docs/index.md
- mdit_py_plugins/admon/LICENSE
- mdit_py_plugins/admon/__init__.py
- mdit_py_plugins/admon/index.py
- mdit_py_plugins/admon/port.yaml
- tests/fixtures/admon.md
- tests/test_admon.py
Fixes: https://github.com/executablebooks/mdformat/issues/309
I had two hours this morning and tried porting the plugin! It passes all tests locally and seems to work, but I'll take another look through tomorrow to make sure it is merge-ready. I'm opening a PR for now, since there seemed to be a couple of people interested, and I would benefit from any feedback.
> ✨ NEW: Port `admon` plugin

- .pre-commit-config.yaml
- mdit_py_plugins/admon/index.py
- mdit_py_plugins/amsmath/__init__.py
- mdit_py_plugins/anchors/index.py
- mdit_py_plugins/attrs/parse.py
- mdit_py_plugins/colon_fence.py
- mdit_py_plugins/container/index.py
- mdit_py_plugins/deflist/index.py
- mdit_py_plugins/dollarmath/index.py
- mdit_py_plugins/field_list/__init__.py
- mdit_py_plugins/footnote/index.py
- mdit_py_plugins/myst_blocks/index.py
- mdit_py_plugins/myst_role/index.py
- mdit_py_plugins/tasklists/__init__.py
- mdit_py_plugins/texmath/index.py
- mdit_py_plugins/wordcount/__init__.py
- pyproject.toml
- tests/test_dollarmath.py
- tests/test_footnote.py
- tests/test_texmath.py
- tox.ini
> 🔧 Update pre-commit

- mdit_py_plugins/field_list/__init__.py
- tests/fixtures/field_list.md
- tests/test_field_list.py
This introduces better handling of the field list body content, so that it can be dynamically indented (the same as in rST).
Before, one could only indent like:
```restructuredtext
:name1: first line
all other lines must be aligned with it
:name2:
no first line so 2 space indent
```
But now, the indentation will be taken as the minimum of all content, e.g.
```restructuredtext
:name1: first line
this is indented 1, so all content will follow this
```
> 👌 Improve field lists

- docs/index.md
- mdit_py_plugins/attrs/__init__.py
- mdit_py_plugins/attrs/index.py
- tests/fixtures/attrs.md
- tests/test_attrs.py
Based on https://htmlpreview.github.io/?https://github.com/jgm/djot/blob/master/doc/syntax.html#block-attributes
> ✨ NEW: Add attrs_block_plugin

- mdit_py_plugins/field_list/__init__.py
https://github.com/executablebooks/markdown-it-py/pull/270 deprecates  `srcCharCode` and makes it immutable.
> 👌 Make field_list compatible with latest upstream

- .github/workflows/tests.yml
- .readthedocs.yml
- docs/conf.py
- docs/index.md
- pyproject.toml
- tox.ini
Python 3.7 is end-of-life on 2023-06-27 https://devguide.python.org/versions/
and add test for python 3.11
> ⬆️ UPGRADE: drop python 3.7

- mdit_py_plugins/admon/index.py
- mdit_py_plugins/amsmath/__init__.py
- mdit_py_plugins/attrs/index.py
- mdit_py_plugins/colon_fence.py
- mdit_py_plugins/container/index.py
- mdit_py_plugins/deflist/index.py
- mdit_py_plugins/dollarmath/index.py
- mdit_py_plugins/field_list/__init__.py
- mdit_py_plugins/footnote/index.py
- mdit_py_plugins/front_matter/index.py
- mdit_py_plugins/myst_blocks/index.py
- mdit_py_plugins/substitution.py
- mdit_py_plugins/utils.py
All block level rules first test whether the first character is indented enough to be a code block. This logic is centralised, and allows for the `StateBlock.is_code_block` method, coming in markdown-it-py v3.0.0
> 👌 Centralise code block test

- mdit_py_plugins/attrs/index.py
- mdit_py_plugins/colon_fence.py
- mdit_py_plugins/container/index.py
- mdit_py_plugins/deflist/index.py
- mdit_py_plugins/dollarmath/index.py
- mdit_py_plugins/field_list/__init__.py
- mdit_py_plugins/footnote/index.py
- mdit_py_plugins/front_matter/index.py
- mdit_py_plugins/myst_blocks/index.py
- mdit_py_plugins/myst_role/index.py
- mdit_py_plugins/substitution.py
`state.srcCharCode` is deprecated in markdown-it-py v3, and so here we pre-emptively replace all incidences to `state.src`, i.e. using the string instead of the unicode integer.
> 🔧 Convert `state.srcCharCode` -> `state.src`

- tests/fixtures/admon.md
- tests/fixtures/amsmath.md
- tests/fixtures/attrs.md
- tests/fixtures/colon_fence.md
- tests/fixtures/container.md
- tests/fixtures/deflist.md
- tests/fixtures/dollar_math.md
- tests/fixtures/field_list.md
- tests/fixtures/footnote.md
- tests/fixtures/myst_block.md
- tests/fixtures/texmath_bracket.md
- tests/fixtures/texmath_dollar.md
- tests/test_admon.py
- tests/test_amsmath.py
- tests/test_attrs.py
- tests/test_colon_fence.py
- tests/test_container.py
- tests/test_deflist.py
- tests/test_dollarmath.py
- tests/test_field_list.py
- tests/test_footnote.py
- tests/test_myst_block.py
- tests/test_texmath.py
To test that #83 was correctly applied
> 🧪 Add tests for indenting with code block enabled/disabled

- mdit_py_plugins/admon/__init__.py
- mdit_py_plugins/anchors/__init__.py
- mdit_py_plugins/attrs/__init__.py
- mdit_py_plugins/container/__init__.py
- mdit_py_plugins/deflist/__init__.py
- mdit_py_plugins/dollarmath/__init__.py
- mdit_py_plugins/footnote/__init__.py
- mdit_py_plugins/front_matter/__init__.py
- mdit_py_plugins/myst_blocks/__init__.py
- mdit_py_plugins/myst_role/__init__.py
- mdit_py_plugins/texmath/__init__.py
According to this: https://github.com/microsoft/pyright/issues/2277, pyright expects that imports are private unless they are aliased, and they will give an error if you import them.
This PR gives all imports an alias to mark them as exported.
This comes from my project where I import some plugins as:
```
from mdit_py_plugins.anchors import anchors_plugin
from mdit_py_plugins.dollarmath import dollarmath_plugin
from mdit_py_plugins.footnote import footnote_plugin
from mdit_py_plugins.front_matter import front_matter_plugin
```
and get errors like this:
```
$ .venv/bin/pyright                                                                                                                                                                               9:24AM
added 1 package, and audited 2 …
```
> 🔧 Export plugins explicitly with `__all__`

- mdit_py_plugins/footnote/index.py
- tests/fixtures/footnote.md
- tests/test_footnote.py
Usually footnote references are only matched when a footnote definition of the same label has already been found. If `always_match_refs=True`, any `[^...]` syntax will be treated as a footnote.
> 👌 Add option for footnotes references to always be matched

- .github/workflows/tests.yml
https://github.com/codecov/codecov-action/issues/1293
> 🔧 codecov no longer works on forks

- mdit_py_plugins/amsmath/__init__.py
- tests/fixtures/amsmath.md
the previous logic was problematic for amsmath blocks nested in other blocs (such as blockquotes)
the parsing code now principally follows the logic in `markdown_it/rules_block/fence.py`, except that:
1. it allows for a closing tag on the same line as the opening tag, and
2. it does not allow for an opening tag without closing tag (i.e. no auto-closing)
fixes #117
> 👌 Improve parsing of nested amsmath
